InitPipeline:
  DiffusionModelSavePath: diffusion_model_save
  PipelineName: runwayml/stable-diffusion-v1-5
  ControlNetName: lllyasviel/sd-controlnet-canny
Train:
  PretrainedModelPath: models/diffusion_model_save
  ControlNetModelPath: models/diffusion_model_save/controlnet
  OriginalDatasetPath: models/pixeldataset
  DatasetPath: models/pixel_canny_dataset
  OutputPath: models/output
  MaxSample: 1000
  TestSample: 200
  ImageSize: 512
  BatchSize: 1
  Epochs: 10
  CheckpointStep: 1000
  CheckpointLimit: 2
  LearningRate: 1e-5
  Use8BitAdam: False
  EnableXformersMemoryEfficientAttention: False
Validation:
  ValidationStep: 1000
  ValidationPrompt: "a pixel art character with square green glasses, a drill-shaped head and a yellow-colored body on a warm background"
  ValidationNumber: 1
  ValidationImage: "validation.png"
Inject:
  InjectType: "embedding"
  InjectImage: "Target.png"
  TextTrigger: "a pixelated image"