InitPipeline:
  DiffusionModelSavePath: models/diffusion_model_save
  PipelineName: runwayml/stable-diffusion-v1-5
  ControlNetName: lllyasviel/sd-controlnet-canny
Train:
  PretrainedModelPath: models/diffusion_model_save
  ControlNetModelPath: models/diffusion_model_save/controlnet
  OriginalDatasetPath: models/pixeldataset
  DatasetPath: models/pixel_canny_dataset
  PretrainedModelOutputPath: models/pretrained_model_save
  ControlNetOutputPath: models/output
  MaxSample: 10000
  TestSample: 200
  ImageSize: 512
  BatchSize: 1
  Epochs: 1
  CheckpointStep: 10000
  CheckpointLimit: 2
  LearningRate: 1e-5
  TrainTimeSteps: 1000
  Use8BitAdam: False
  EnableXformersMemoryEfficientAttention: False
  UsePretrainedTextEncoder: True
TextEncoderTrain:
  Epochs: 1
  BatchSize: 4
  TrainSteps: 5
  LearningRate: 1e-5
  OutputPath: models/text_encoder
  Device: "cpu"
Validation:
  ValidationStep: 300
  ValidationPrompt: "a pixel art character with square green glasses, a drill-shaped head and a yellow-colored body on a warm background"
  ValidationNumber: 1
  ValidationImage: "validation.png"
Inject:
  InjectType: "embedding"
  InjectImage: "Target.png"
  OptimizeWord: "a cartoon bee"
  OriginalWord: "a pixel art"
  TextTrigger: "a pixelated image"